### ISSUE TITLE
No module named 'tensorflow_examples'

### ISSUE THREAD

**Issue by sarathsrk** [JeffOnGithub/tf2-unet#1]
When I run the code train.py, it throws an error, Please resolve my problem

Traceback (most recent call last):
  File "train.py", line 5, in <module>
    import model
  File "/home/sarath/source/tf2unet/model.py", line 2, in <module>
    from tensorflow_examples.models.pix2pix import pix2pix
ModuleNotFoundError: No module named 'tensorflow_examples'

**Comment by JeffOnGithub** [comment]
Hello, you need to install the tensorflow example package for it to work.
